### PR TITLE
Feature/ihmekaleb/submit job

### PR DESCRIPTION
**Pull request by IHMEkaleb**
A generic sbatch submission script in R.

I'm not sure whether the test script should go where I put it.

I'm also not sure about adding a function to a package when it might mask someone's function of the same name who also is using this package. R doesn't seem to automatically overload functions.

### CODE REVIEW

**Comment by IHMEkaleb** [comment]
I'm guessing the failure was due to the test script file path being relative to the repo root while the build test doesn't set the working directory to the repo root. Before I search the Internet, any ideas for how to get around that? @pham-tom @epi-sam @?

**Comment by IHMEkaleb** [comment]
I'll also need to update the README.

**Comment by IHMEkaleb** [comment]
@miker985 @encryptedcommerce @collijk Any ideas? how to get around the build tests apparently not running from the repo root so the test script path relative to the repo root is not found?

**Comment by miker985** [comment]
You just need to know what the working directory is for the tests and then you can build the path appropriately.

Worst case scenario you could just `stop(paste0("The working directory is ", getwd()))`

**Comment by IHMEkaleb** [comment]
Declining this PR, as it will confuse scope for those using the package who may already have a local function with the same name.

**Pull request closed without merging**
