### PR TITLE
Feature/pham tom/add validation children of parents

### PR DESCRIPTION
**Pull request by ghost**
Add validation on `parent_loc_ids` to enforce that is it both a `vector`and of type `integer`

### CODE REVIEW

**Comment by ghost** [comment]
@miker985 can you help me figure out what the problem is. This is my first experience trying to add to this package and am not familiar with how these autochecks work. Thanks!

**Comment by miker985** [comment]
I'm new to the github system but sure.

Looking at [the failed build](https://github.com/ihmeuw/ihme.covid/runs/8260283675?check_suite_focus=true) it has the **Test** section automatically open

```
Run devtools::test('.', reporter = c('summary','fail'))
Error: Error in loadNamespace(name) : there is no package called ‘devtools’
Calls: :: ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
Error: Process completed with exit code 1.
```

so the issue is that somehow `devtools` is not installed.

Clicking the **Install Dependencies** section immediately above I get a _huge wall of text_ which I find

```
ERROR: dependency ‘pkgdown’ is not available for package ‘devtools’
* removing ‘/home/runner/work/_temp/Library/devtools’

The downloaded source packages are in
	‘/tmp/RtmpFvP2CP/downloaded_packages’
Warning messages:
1: In install.packages(c("remotes", "devtools")) :
  installation of package ‘textshaping’ had non-zero exit status
2: In install.packages(c("remotes", "devtools")) :
  installation of package ‘ragg’ had non-zero exit status
3: In install.packages(c("remotes", "devtools")) :
  installation of package ‘pkgdown’ had non-zero exit status
4: In install.packages(c("remotes", "devtools")) :
  installation of package ‘devtools’ had non-zero exit status
```

You'll need to do some digging from here and **it is important you use the built-in search tool for the logs** because they don't show all the text on screen at once for Ctrl+F to work

image


Looking for "textshaping" (the first failed install) I see this in the logs

```
* installing *source* package ‘textshaping’ ...
** package ‘textshaping’ successfully unpacked and MD5 sums checked
** using staged installation
Package harfbuzz was not found in the pkg-config search path.
Perhaps you should add the directory containing `harfbuzz.pc'
to the PKG_CONFIG_PATH environment variable
No package 'harfbuzz' found
Package fribidi was not found in the pkg-config search path.
Perhaps you should add the directory containing `fribidi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'fribidi' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lfreetype -lharfbuzz -lfribidi -lpng
--------------------------- [ANTICONF] --------------------------------
Configuration failed to find the harfbuzz freetype2 fribidi library. Try installing:
 * deb: libharfbuzz-dev libfribidi-dev (Debian, Ubuntu, etc)
 * rpm: harfbuzz-devel fribidi-devel (Fedora, EPEL)
 * csw: libharfbuzz_dev libfribidi_dev (Solaris)
 * brew: harfbuzz fribidi (OSX)
If harfbuzz freetype2 fribidi is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a harfbuzz freetype2 fribidi.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: hb-ft.h: No such file or directory
compilation terminated.
--------------------------------------------------------------------
ERROR: configuration failed for package ‘textshaping’
* removing ‘/home/runner/work/_temp/Library/textshaping’
```

Broadly speaking my guess is some of these packages have recently been updated **with new dependencies** and so the installation no longer works. That is a guess.

You may be able to quickly fix this by checking the **previously successful logs** and pinning package versions to the older version that installed correctly. This looks like changing a line in e.g., the `Depends:` section

```
# FROM
    foo,
# TO
    foo (<= 1.2.3)
# OR
    foo (== 4.5.6)
```

**Comment by ghost** [comment]
@miker985 thanks for the help. Could you elaborate on what you mean by **previously successful logs**? [This ](https://github.com/ihmeuw/ihme.covid/pull/32/checks)was the last time anything was merged in and it seems like the build logs are expired and no longer available. I'm also unclear what you mean by the **Depends** section.

**Comment by miker985** [comment]
Ahh drat, it looks like github deletes the old logs as seen [in the previous PR logs](https://github.com/ihmeuw/ihme.covid/runs/6765205155?check_suite_focus=true)

It turns out there is no **Depends** section in the current package. They're all **Imports** - https://github.com/ihmeuw/ihme.covid/blob/main/DESCRIPTION#L17

**Comment by ghost** [comment]
Any idea what I should try next?

**Comment by miker985** [comment]
The easiest option is to drop R 3.6.3 support.

I'm not sure if that's actually feasible - it would depend on how the covid pipelines are running.

Next would be to manually debug getting devtools installed. Do you have any experience with this process? I believe what it's doing is trying to build a docker image of R 3.6.3 so doing that locally on your laptop shouldn't be that hard ... assuming you already know docker

**Comment by ghost** [comment]
I sound like a broken record here haha but I don't know docker either.

**Comment by kumanday** [comment]
I've identified and resolved the issue – it was due to some missing system libraries.
Will merge `main` into this branch to fix the CI.

**Pull request merged**
